server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: host.docker.internal:8848
      discovery:
        server-addr: host.docker.internal:8848
  config:
    import:
      - optional:nacos:gateway.yml
