server:
  port: 8010
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat # add ,wall if need sql firewall
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      driver-class-name: org.postgresql.Driver
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: false
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
  config:
    import:
      - nacos:order-server.yml


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: unsw.comp9900.demo.order.entity
  mapper-locations: classpath:/mapper/*.xml

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      order-service-group: default
    grouplist:
      default: 127.0.0.1:8091

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
