server:
  port: 8010
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres

    druid:
      driver-class-name: org.postgresql.Driver
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"

  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: unsw.comp9900.demo.order.entity
  mapper-locations: classpath:/mapper/*.xml